### ISSUE TITLE
For HMM, viterbi pstate probabilities ignore obstrue

### ISSUE THREAD

**Issue by helmingstay** [chjackson/msm#46]
The following is based on my reading of the `obstrue` section of `help("msm")` and previous discussion of `obstrue` in Issues #40 and #41. Apologies in advance if I've misinterpreted "true state" here.

This simplified example looks at `obstrue` in a HMM *without* censoring.  I expect `obstrue` to indicate the true hidden state here, and for this to be reflected in the `pstate` matrix from `viterbi.msm`. In this examlpe, I see that `fitted` always equals `obstrue` (when provided), but the relevant `pstate` seem to ignore the information in `obstrue`.

```
 library(msm)
set.seed(8)

pars <- within(list(), {
    npair = 20
    ## transition rate
    q = 0.05
    prob=list(S=0.2, I=0.8)
    deltat=5
    tmax=20
})

## Full example
sim.grid <- with(pars,
    expand.grid(time=seq(0,tmax,by=deltat), subject=1:npair)
)

## initial conditions / observation model
config <- list(
    qmat = rbind(
        c(0, pars$q),
        c(0, 0)
    ),
    hmod = list(
        S=hmmBinom(size=1, prob=0.2),
        I=hmmBinom(size=1, prob=0.8)
    )
)

sim.dat <- simmulti.msm(sim.grid, 
    config$qmat, drop.absorb=F,
    hmodel=list(
        S=hmmBinom(size=1, prob=0.2),
        ## sim uses larger size
        I=hmmBinom(size=2, prob=0.8)
    )
)

panel <- subset(sim.dat, select=c(subject, time, obs))
panel <- within(panel, {
    ## force state 2
    obstrue <- ifelse(obs==2, 2, NA)
    obs <- ifelse(obs>1, 1, 0)
})

result <- msm(data=panel,
    obs ~ time, subject=subject,
    obstrue=obstrue,
    qmatrix=config$qmat,
    hmodel=config$hmod,
    fixedpars=T
)

pred <- merge(
    panel,
    viterbi.msm(result),
    by=c('subject', 'time'), sort=F
)

## I expect pstate.2==1 when obstrue==2 
expect <- subset(pred, obstrue==2)
```

**Comment by chjackson** [comment]
Thanks, I think this is now fixed in https://github.com/chjackson/msm/commit/ac6ab3a6f0401499c440513844e7b01f53947d6e .  The forward and backward probabilities both needed to be modified to account for the case when the true state is known.  I've put in a unit test for this based on your code, if you don't mind. 

This bug took much longer than it should to find, because my C code for the Viterbi algorithm is so badly written.   It dates back to when I was a student.   It needs a full rework, but it'd take ages, and I don't work with this kind of model much these days.   Any contributions from anyone reading and interested in this are welcome!

**Comment by helmingstay** [comment]
Thanks so much for your attention to this. I admit that my C is weak, sorry I'm not more help here.
FYI, I'm still seeing this issue when I use an hmmMV in hmodel. I will work on an MWE (see also #47).

**Comment by chjackson** [comment]
Closed with https://github.com/chjackson/msm/issues/47
